### ISSUE TITLE
crash when press more button

### ISSUE THREAD

**Issue by paynd** [SidhNor/SITracker#53]
Hi there!
I've got a crash when press more settings on actionbar.
nexus 4, android 5.0.1
```
E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.andrada.sitracker, PID: 12755
    java.lang.RuntimeException: Failed to resolve attribute at index 6
            at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:603)
            at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:6423)
            at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6591)
            at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:735)
            at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:679)
            at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:62)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at com.android.internal.view.menu.MenuPopupHelper$MenuAdapter.getView(MenuPopupHelper.java:375)
            at com.android.internal.view.menu.MenuPopupHelper.measureContentWidth(MenuPopupHelper.java:211)
            at com.android.internal.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:144)
            at android.widget.ActionMenuPresenter$OpenOverflowRunnable.run(ActionMenuPresenter.java:759)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by SidhNor** [comment]
I believe this was fixed in ffa387fcdd5a67ce29ba956ab106570615b09377 release
